# Generated by Django 4.2.7 on 2023-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_accounttype_alter_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('apointedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
